language: python

env:
  - BUILD=0

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda info -a

install:
  - conda create -n test-env --yes
  - source activate test-env
  - pip install flake8 pytest
  - pip install -e .

script:
  - source activate test-env
  - py.test
  - flake8
